name: g60
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  google_fonts: ^2.1.0
  after_layout: ^1.1.0
  ntp: ^2.0.0
  animate_do: ^2.0.0
  firebase_core: ^1.3.1
  firebase_auth: ^3.0.0
  provider: ^5.0.0
  cloud_firestore: ^2.4.0
  uuid: ^3.0.4
  intl: ^0.17.0
  hexcolor: ^2.0.4
  get_it: ^7.1.3
  stacked_services: ^0.8.9
  rxdart: ^0.27.1
  websafe_svg: ^2.0.0
  nearby_connections: ^3.1.0
  video_player: ^2.1.10
  chewie: ^1.2.2
  device_info_plus: ^2.1.0


  # APP ONLY ONLY PLUGIN
  #firebase_database: ^7.1.2

  # WEB ONLY PLUGIN
  firebase: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/


